fix deploy docker compose error

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -4,11 +4,15 @@
 
 echo "INFO: Welcome to \"DevOps with Saeid\" class (www.devops-with-saeid.com)."
 
-which docker compose &> /dev/null
-
-if [ $? -ne 0 ]; then
-    echo "ERROR: docker-compose is not installed."
-    exit 1
+if [[ $(docker info -f json | jq '.ClientInfo.Plugins | any(.Name == "compose")') == "true" ]]; then
+    DOCKER_COMPOSE_COMMAND="docker compose"
+else
+    DOCKER_COMPOSE_COMMAND="docker-compose"
+    which docker-compose &> /dev/null
+    if [ $? -ne 0 ]; then
+        echo "ERROR: docker-compose is not installed."
+        exit 1
+    fi
 fi
 
 mkdir -p certs
@@ -35,7 +39,7 @@ fi
 
 export JENKINS_DOCKER_REGISTRY_IP=${SYSTEM_IP_ADDRESSES[0]}
 
-docker compose up -d
+$DOCKER_COMPOSE_COMMAND up -d
 
 echo "INFO: jenkins-stack deployed successfully."
 
